id: affe6711f9a14273827a82048083c0c1
initial_creation_type: ocr
source_metadata:
  volumes:
    524108eaa2934a65bab1e84f3cd556fd:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: དངོས་པོ་སྦྱོང་བ།
      total_pages: 1902
      volume_number: 26
